'''
Created on Mar 13, 2014

@author: Dario Bonino <dario.bonino@polito.it>
'''
#!/usr/bin/python

import os

def say(text, language = 'en'):
    #prepare the command to fetch the mp3 file generated by gogle tts
    wget_line = 'wget -q -U Mozilla -O test.mp3 "http://translate.google.com/translate_tts?ie=UTF-8&tl='+language+'&q='+text+'"'

    #fetch the mp3
    os.system(wget_line)

    #play it (system dependent)
    os.system("mplayer -quiet -nolirc -msglevel all=-1 test.mp3")


if __name__=="__main__":

    string = ""
    while (string != "exit"):
        string = raw_input("Insert text here:\n>")
        if(string == "exit"):
            tts_text = "Goodbye!"
        else:
            tts_text = string.replace(" ","+")

        say(tts_text)    
